const express = require('express');
const router = express.Router();
const jobControllers = require('../controllers/jobControllers');
const authenticateToken = require('../utils/authenticateToken');
router.use(authenticateToken);
router.post('/createjob', jobControllers.createJobPost);
router.get('/showjobs', jobControllers.showJobs);
router.get('/showjobs/:jobId', jobControllers.showJobDetails);
router.post('/apply', jobControllers.applyToJob);
router.get('/showjobs/employer/:employerId', jobControllers.showJobsByEmployer);
router.get('/showjobs/user/:userId', jobControllers.showJobsByUser);
module.exports = router;
